sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
install: pip install tox-travis
matrix:
  allow_failures:
    python:
      - "3.8-dev"
  include:
    - python: 3.8-dev
      dist: xenial
      sudo: true
script: tox
