sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
  - "pypy"
  - "pypy3.5"
  - "nightly"
install: pip install coverage
matrix:
  allow_failures:
    python:
      - "nightly"
      - "3.10-dev"
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
script:
    - coverage run -m py.test tests
    - bash <(curl -s https://codecov.io/bash)
